app_name = "use-gin"
server_port = ":8443"
runmode = "release" # debug/release/test

[https]
enable = true
cert = "conf/ssl/cert.pem"
key = "conf/ssl/key.pem"

[log]
dirname = "logs"
rotation_hours = 24
save_days = 7
log_format = "json"  # json/txt

[mail]
smtp_host = "smtp.example.com"
port = 587
user = "no-reply@example.com"
password = "your-password"
mail_to = [
    "name1@xxx.com",
    "name2@xxx.com",
]

[auth]
jwt_secret = "3f017bc64bb365167987e307cc41c9f4"  # for /login
jwt_lifetime = 86400  # seconds, for jwt token that /login generate
jwt_max_lifetime = 600  # for jwt token that user generate
# seconds, for api signature, considering the time gap between client and server
apisign_lifetime = 600

# dbtype could be mysql/mssql/postgres/sqlite3
[rdbs]
    [rdbs.mysql]
    dbtype = "mysql"
    address = "localhost:3306"
    dbname = "demo"  # NOTE: create the database manually
    user = "root"
    password = "123456"
    max_idle_conns = 10
    max_open_conns = 100

    [rdbs.postgresql]
    dbtype = "postgres"
    address = "127.0.0.1:5432"
    dbname = "demo"
    user = "sre"
    password = "sre.im"
    max_idle_conns = 10
    max_open_conns = 100

[mongo]
address = "localhost:27017"
dbname = "demo"
username = ""
password = ""

[kafka]
brokers = [
    "kafka01.sre.im:9092",
    "kafka02.sre.im:9092",
    "kafka03.sre.im:9092",
]
producer_topic = ""
consumer_topic = ""
consumer_group = ""
keepalive = 10

[influxdb]
address = "http://127.0.0.1:8086"
username = ""
password = ""
dbname = "demo"
measurement = "test"

[redis]
address = "127.0.0.1:6379"
db = 0
password = ""
max_idle = 30
max_active = 30
idle_timeout = 180

[redis_cluster]
nodes = [
    "10.10.10.1:7001",
    "10.10.10.2:7001",
    "10.10.10.3:7001"
]
secret = ""
pool_size = 20
pool_timeout = 60

# disable this feature when the item value is []
[acl]
allow_url = []
allow_ip = ["127.0.0.1", "::1"]
