app_name = "use-gin"
server_port = ":8000"
runmode = "release" # debug/release/test

[log]
dirname = "logs"
rotation_hours = 24
save_days = 7
log_format = "json"  # json/txt

[mail]
smtp_host = "smtp.example.com"
port = 587
user = "no-reply@example.com"
password = "your-password"
mail_to = [
    "name1@xxx.com",
    "name2@xxx.com",
]

[auth]
jwt_secret = "3f017bc64bb365167987e307cc41c9f4"  # for /login
jwt_lifetime = 2880  # minutes, for /login
# seconds, for api signature, considering the time gap between client and server
apisign_lifetime = 600

[mysql]
dbtype = "mysql"  # mysql/mssql/postgres/sqlite3
address = "127.0.0.1:3306"
dbname = "demo"  # create the database manually
user = "sre"
password = "sre.im"

[postgresql]
dbtype = "postgres"
address = "127.0.0.1:5432"
dbname = "demo"
user = "sre"
password = "sre.im"

[kafka]
brokers = [
    "kafka01.sre.im:9092",
    "kafka02.sre.im:9092",
    "kafka03.sre.im:9092",
]
producer_topic = ""
consumer_topic = ""
consumer_group = ""

[influxdb]
address = "http://127.0.0.1:8086"
username = ""
password = ""
dbname = ""
measurement = ""

# disable this feature when the item value is []
[acl]
allow_url = []
allow_ip = ["127.0.0.1", "::1"]
