basePath: /api
host: ginner.sre.im:8000
info:
  contact:
    email: i@sre.im
    name: Windvalley
  description: For developing high quality applications(Web API) efficiently by Go Gin.
  license:
    name: MIT
    url: https://github.com/windvalley/ginner/blob/master/LICENSE
  title: ginner API
  version: 0.0.1
paths: {}
swagger: "2.0"
